mod about;
mod android;
mod contribute;
mod discord;
mod guides;
mod home;
mod ios;
mod privacy;
mod reset;
mod shared_deck;
mod verify;

pub use about::About;
pub use android::Android;
pub use contribute::Contribute;
pub use discord::Discord;
pub use guides::{GuidePage, Guides};
pub use home::Home;
pub use ios::Ios;
pub use privacy::Privacy;
pub use reset::Reset;
pub use shared_deck::SharedDeck;
pub use verify::Verify;
