# Linker configurations for x86_64-unknown-linux-gnu
# Use ONE section at a time. Comment out others.
# - mold: Fastest, use for debug (cargo build).
# - lld: Fast, alternative for debug (cargo build).
# - GNU ld: Stable, use for release (cargo build --release).

# GNU ld (Release, stable, slower)
# [target.x86_64-unknown-linux-gnu]
# rustflags = []

# lld (Development, faster, less stable)
# [target.x86_64-unknown-linux-gnu]
# rustflags = ["-C", "linker=clang", "-C", "link-arg=-fuse-ld=lld"]

# mold (Development, fastest, less stable)
# (Currently uncommented)
[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=/usr/bin/mold"]


# Switch linkers:
# 1. Uncomment desired section, comment others.
# 2. Run `cargo clean && cargo build` (debug) or `cargo build --release` (release).

# Verify linker:
# - Verbose: `cargo build --verbose` or `cargo build --release --verbose`
#   - mold: `-fuse-ld=/usr/bin/mold`
#   - lld: `-fuse-ld=lld`
#   - GNU ld: No `-fuse-ld` or `/usr/bin/ld`
# - Binary: `readelf --string-dump .comment target/debug/deck-builder-api` (debug) or `target/release/deck-builder-api` (release)
#   - mold: `mold X.Y.Z`
#   - lld: `Linker: LLD X.Y.Z`
#   - GNU ld: No mold/lld, may show `GCC: (GNU)`