[application]
name = "Zwipe"

[bundle]
identifier = "com.scadoshi.zwipe"
publisher = "scadoshi"

[web.app]

# HTML title tag content
title = "zwipe"

# Additional CSS style files
style = ["/main.css"]

[ios.plist]
CFBundlePackageType = "APPL"
MinimumOSVersion = "16.0"
DTPlatformName = "iphoneos"
DTPlatformVersion = "26.4"
DTSDKName = "iphoneos26.4"
DTXcode = "2640"
DTXcodeBuild = "17E192"
DTCompiler = "com.apple.compilers.llvm.clang.1_0"
UISupportedInterfaceOrientations = ["UIInterfaceOrientationPortrait"]
"UISupportedInterfaceOrientations~ipad" = ["UIInterfaceOrientationPortrait"]

[web.resource.dev]
